(defun remote-connect ()
  (interactive)
  (let* ((user-name (read-string "User: "))
	 (ip-address (read-string "IP: "))
	 (dir (format "/home/%s" user-name)))
    (dired (format "/ssh:%s@%s:%s" user-name ip-address dir))))

(defun load-init ()
  (interactive)
  (load-file "~/.emacs.d/init.el"))
